Documentation for partial disabled receive locations
msnehagup/biztalk-docs pull request #47
Opened 2020-02-10 22:07 UTC by pravagar

2020-02-10 22:43 UTC, SanjivGupta-SanGupt approved these changes

2020-02-10 22:43 UTC, SanjivGupta-SanGupt commented on biztalk/technical-guides/how-to-enable-receive-location-fault-tolerance.md
> +To make your environment highly available, you can create two or more host instances for each receiving host. In such environment, receive workloads will be distributed between different host instanc
… three host instances (A, B and C)
correct there to three 
hosts to host

2020-02-10 22:46 UTC, msnehagup commented on biztalk/install-and-config-guides/whats-new-in-biztalk-server-2020.md
> +|Audit Log|Making BizTalk further secure by maintaining audit trails of all management operation.<br/><br/>[Configuring and Viewing Audit Logs](https://docs.microsoft.com/en-us/biztalk/core/audit-man
refer to relative path:
(../core/audit-management-operations.md)

2020-02-10 22:47 UTC, msnehagup commented on biztalk/install-and-config-guides/whats-new-in-biztalk-server-2020.md
> +|Audit Log|Making BizTalk further secure by maintaining audit trails of all management operation.<br/><br/>[Configuring and Viewing Audit Logs](https://docs.microsoft.com/en-us/biztalk/core/audit-man
Please update ms.date as well

2020-02-10 22:51 UTC, msnehagup commented on biztalk/technical-guides/how-to-enable-receive-location-fault-tolerance.md
> +---
since this is a new file, you also need to update the TOC file:
https://github.com/msnehagup/biztalk-docs/blob/pravagar/partialdrl/biztalk/TOC.md

2020-02-10 22:58 UTC, msnehagup commented on biztalk/install-and-config-guides/whats-new-in-biztalk-server-2020.md
> +|Additional updates|<ul><li>Move to new long term supported Microsoft OLEDB Driver for SQL Server. </li><br/><li>Support for SSO Affiliate applications in SFTP adapter.</li><br/><li>SQL Availability
use relative path to link to file:
(../technical-guides/how-to-enable-receivelocation-faulttolerance.md)

2020-02-11 19:09 UTC, msnehagup requested changes

2020-02-11 19:09 UTC, msnehagup commented on biztalk/TOC.md
> +#### [Enable Receive Location fault tolerance](technical-guides/how-to-enable-receive-location-fault-tolerance)
Pages under 'technical-guides' folder should be added under the Technical Guides section in the TOC.
If you want to add this page under in the Core docs in TOC, please move your page to 'core' folder

2020-02-11 19:09 UTC, msnehagup commented on biztalk/TOC.md
> +#### [Enable Receive Location fault tolerance](technical-guides/how-to-enable-receive-location-fault-tolerance)
Also, while including the page in TOC, make sure to have the '.md' file extension

2020-02-13 19:14 UTC, msnehagup commented on biztalk/install-and-config-guides/whats-new-in-biztalk-server-2020.md
> +|XSLT 3.0|New extensible model for runtime map execution, out of box wiring to work with Saxon XSLT3.0. <br/><br/>[XSLT Transform Engine](../core/technical-reference/xslt-transform-engine-grid-proper
please don't change the links that refer to articles under "technical-reference" - those do not work with relative paths

2020-02-13 19:32 UTC, msnehagup approved these changes

2020-02-13 19:42 UTC, merged